### ISSUE TITLE
If its named OrgChart....

### ISSUE THREAD

**Issue by Stefdv** [shawncao/orgchart#1]
Then why is the demo an Donut ?
I need an example for an organisation chart Please

**Comment by johncao1** [comment]
Hi @Stefdv. I looked into the issue and there was a set timeout on the test page. It changed the orgchart into the donut chart after two seconds and wouldn't change back.

I fixed the problem by removing the timeout function and adding two buttons so that you could choose which chart to display. By default, the page will display the orgchart when it loads.

**Comment by Stefdv** [comment]
Tx :)
